// Import portfolio preview images
import darkCyberPreview from '../../assets/portfolioPreview/Dark Cyber Portfolio.JPG';
import terminalPreview from '../../assets/portfolioPreview/Terminal Portfolio.JPG';
import artistPreview from '../../assets/portfolioPreview/Artist Portfolio.JPG';
import cyberSecurityPreview from '../../assets/portfolioPreview/Cyber Security Portfolio.JPG';

// Template Presets - Pre-configured portfolio structures for different themes
export const TEMPLATE_PRESETS = {
    darkCyber: {
        name: 'Dark Cyber',
        description: 'Futuristic cyberpunk theme with neon accents and dark backgrounds - No external links',
        preview: darkCyberPreview,
        content: [
            {
                type: 'Hero',
                props: {
                    id: 'hero-darkcyber',
                    template: 'darkCyber',
                    name: 'Alex Cyber',
                    title: 'Full Stack Developer & Cybersecurity Specialist',
                    description: 'Crafting secure digital experiences with cutting-edge technologies. Specializing in blockchain, AI, and advanced security protocols.',
                    image: 'https://placehold.co/400x400/111827/00FFFF?text=CYBER.DEV',
                    email: 'alex@cyber.dev',
                    backgroundColor: 'bg-black',
                    accentColor: 'cyan',
                    yearsCount: '5+',
                    yearsLabel: 'Years Experience',
                    projectsCount: '50+',
                    projectsLabel: 'Projects Delivered',
                    clientsCount: '30+',
                    clientsLabel: 'Happy Clients',
                    secondaryButtonText: 'Contact Me',
                },
            },
            {
                type: 'About',
                props: {
                    id: 'about-darkcyber',
                    template: 'darkCyber',
                    title: 'About Me',
                    content:
                        "Passionate about pushing the boundaries of what's possible in the digital realm. I combine deep technical expertise with creative problem-solving to build secure, scalable applications that make a difference.",
                    resumeUrl: '/shared/alex-cyber-resume',
                    backgroundColor: 'bg-gradient-to-br from-gray-900 via-black to-gray-800',
                    accentColor: 'cyan',
                    showCTA: true,
                    skills: [
                        { name: 'React/Next.js', level: 95, category: 'frontend' },
                        { name: 'Node.js/Express', level: 90, category: 'backend' },
                        { name: 'PostgreSQL', level: 85, category: 'database' },
                        { name: 'Docker/K8s', level: 88, category: 'tools' },
                        { name: 'Cybersecurity', level: 92, category: 'security' },
                    ],
                    yearsExperience: '5+',
                    projectsCompleted: '50+',
                    clientsSatisfied: '30+',
                },
            },
            {
                type: 'Skills',
                props: {
                    id: 'skills-darkcyber',
                    template: 'darkCyber',
                    title: 'Technical Arsenal',
                    backgroundColor: 'bg-black',
                    accentColor: 'cyan',
                    skills: [
                        { name: 'React', level: 95, category: 'Frontend' },
                        { name: 'Node.js', level: 90, category: 'Backend' },
                        { name: 'Python', level: 88, category: 'Backend' },
                        { name: 'PostgreSQL', level: 85, category: 'Database' },
                        { name: 'Docker', level: 87, category: 'DevOps' },
                        { name: 'AWS', level: 83, category: 'Cloud' },
                        { name: 'Penetration Testing', level: 92, category: 'Security' },
                        { name: 'Blockchain', level: 78, category: 'Emerging Tech' },
                    ],
                },
            },
            {
                type: 'Projects',
                props: {
                    id: 'projects-darkcyber',
                    template: 'darkCyber',
                    title: 'Featured Projects',
                    backgroundColor: 'bg-gradient-to-br from-slate-900 via-gray-900 to-black',
                    accentColor: 'cyan',
                    projects: [
                        {
                            title: 'SecureVault',
                            description: 'Blockchain-based secure document storage with end-to-end encryption. Built with modern security principles and zero-knowledge architecture.',
                            image: 'https://placehold.co/400x250/111827/00FFFF?text=SecureVault',
                            technologies: 'React, Solidity, IPFS, Web3',
                            status: 'completed',
                            features: 'End-to-end encryption, Zero-knowledge proof, Decentralized storage',
                        },
                        {
                            title: 'CyberDash',
                            description: 'Real-time cybersecurity monitoring dashboard for enterprise systems. Provides comprehensive threat detection and response capabilities.',
                            image: 'https://placehold.co/400x250/111827/00FFFF?text=CyberDash',
                            technologies: 'Next.js, Python, Redis, WebSocket',
                            status: 'completed',
                            features: 'Real-time monitoring, Threat detection, Custom alerts',
                        },
                        {
                            title: 'AI Threat Detector',
                            description: 'Machine learning system for detecting advanced persistent threats. Uses deep learning algorithms to identify sophisticated attack patterns.',
                            image: 'https://placehold.co/400x250/111827/00FFFF?text=AI+Threat+Detector',
                            technologies: 'Python, TensorFlow, Elasticsearch, Kafka',
                            status: 'completed',
                            features: 'Machine learning, Pattern recognition, Automated response',
                        },
                    ],
                },
            },
            {
                type: 'Contact',
                props: {
                    id: 'contact-darkcyber',
                    template: 'darkCyberSec',
                    title: 'SECURE COMMUNICATION CHANNEL',
                    subtitle: 'Establish encrypted connection for confidential discussions and security consultations',
                    description:
                        'All communications are monitored, encrypted, and logged for security purposes. Response time: 24-48 hours for standard inquiries, immediate for critical security incidents.',
                    backgroundColor: 'bg-black',
                    accentColor: 'cyan',
                    sectionLabels: {
                        communicationChannelsTitle: 'Communication Channels',
                        operatingScheduleTitle: 'Operating Schedule',
                        securityProtocolsTitle: 'Security Protocols',
                        clearanceInfoTitle: 'Security Clearance Information',
                    },
                    operatingHoursLabels: {
                        standardHoursLabel: 'Standard Hours:',
                        emergencyResponseLabel: 'Emergency Response:',
                        internationalLabel: 'International:',
                        timeZoneLabel: 'Time Zone:',
                    },
                    clearanceLabels: {
                        publicInquiriesLabel: 'Public Inquiries',
                        consultingWorkLabel: 'Consulting Work',
                        governmentContractsLabel: 'Government Contracts',
                        emergencyResponseLabel: 'Emergency Response',
                    },
                    contactMethods: [
                        {
                            type: 'secure-email',
                            label: 'Encrypted Email',
                            value: 'alex@cyber.dev',
                            protocol: 'PGP Encrypted',
                            icon: '🔐',
                            securityLevel: 'high',
                            responseTime: '24h',
                        },
                        {
                            type: 'secure-phone',
                            label: 'Secure Line',
                            value: '+1 (555) CYBER-SEC',
                            protocol: 'Signal/Wire',
                            icon: '📞',
                            securityLevel: 'medium',
                            responseTime: 'immediate',
                        },
                        {
                            type: 'secure-chat',
                            label: 'Secure Chat',
                            value: '@CyberSecPro',
                            protocol: 'Element/Matrix',
                            icon: '💬',
                            securityLevel: 'high',
                            responseTime: '1-4h',
                        },
                        {
                            type: 'location',
                            label: 'Secure Facility',
                            value: 'Classified Location, DC Metro',
                            protocol: 'Physical Security',
                            icon: '🏢',
                            securityLevel: 'maximum',
                            responseTime: 'by appointment',
                        },
                    ],
                    clearanceInfo: {
                        publicInquiries: 'No clearance required',
                        consultingWork: 'Secret clearance preferred',
                        governmentContracts: 'Top Secret/SCI required',
                        emergencyResponse: 'Immediate clearance verification',
                    },
                    operatingHours: {
                        standard: 'Mon-Fri: 0800-1800 EST',
                        emergency: '24/7 Incident Response',
                        international: 'Global coverage available',
                        timeZone: 'Eastern Standard Time (UTC-5)',
                    },
                    securityProtocols: [
                        { value: 'End-to-end encryption for all communications' },
                        { value: 'Multi-factor authentication required' },
                        { value: 'Security clearance verification process' },
                        { value: 'Confidentiality agreements mandatory' },
                        { value: 'Incident response within 1 hour' },
                        { value: 'Secure file transfer protocols only' },
                    ],
                },
            },
            {
                type: 'Footer',
                props: {
                    id: 'footer-darkcyber',
                    template: 'darkCyber',
                    backgroundColor: 'bg-black',
                    textColor: 'text-cyan-400',
                    description: 'Crafting digital experiences at the intersection of innovation and security.',
                    footerSections: [
                        {
                            title: 'Navigation',
                            links: [
                                { label: 'About', href: '#about' },
                                { label: 'Skills', href: '#skills' },
                                { label: 'Projects', href: '#projects' },
                                { label: 'Contact', href: '#contact' },
                            ],
                        },
                        {
                            title: 'Services',
                            links: [
                                { label: 'Web Development', href: '#services' },
                                { label: 'Security Consulting', href: '#services' },
                                { label: 'Code Review', href: '#services' },
                                { label: 'Training', href: '#services' },
                            ],
                        },
                    ],
                },
            },
        ],
    },
    darkTerminal: {
        name: 'Dark Terminal',
        description: 'Command-line inspired theme with terminal aesthetics and coding vibes',
        preview: terminalPreview,
        content: [
            {
                type: 'Hero',
                props: {
                    id: 'hero-terminal',
                    template: 'darkTerminal',
                    name: 'dev@terminal',
                    title: 'Full Stack Developer',
                    description: '> Passionate developer who speaks fluent code and thinks in algorithms. Building scalable solutions one commit at a time.',
                    image: 'https://placehold.co/400x400/000000/00FF00?text=$+DEV',
                    backgroundColor: 'bg-black',
                    terminalTheme: 'matrix',
                    linesOfCode: '100K+',
                    coffeeConsumed: '9000+',
                    bugsFixed: '500+',
                    resumeUrl: '/shared/terminal-dev-resume',
                    secondaryButtonText: 'Download CV',
                },
            },
            {
                type: 'About',
                props: {
                    id: 'about-terminal',
                    template: 'darkTerminal',
                    title: '$ cat about.txt',
                    content: 'A passionate developer who finds beauty in clean code and elegant solutions. I enjoy tackling complex problems and turning ideas into reality through code.',
                    email: 'dev@terminal.com',
                    backgroundColor: 'bg-black',
                    terminalTheme: 'matrix',
                    showCTA: true,
                    skills: [
                        { name: 'JavaScript', level: 95, category: 'Languages' },
                        { name: 'Python', level: 90, category: 'Languages' },
                        { name: 'TypeScript', level: 88, category: 'Languages' },
                        { name: 'React', level: 92, category: 'Frontend' },
                        { name: 'Vue.js', level: 85, category: 'Frontend' },
                        { name: 'Node.js', level: 88, category: 'Backend' },
                        { name: 'Express', level: 87, category: 'Backend' },
                        { name: 'MongoDB', level: 83, category: 'Database' },
                    ],
                },
            },
            {
                type: 'Skills',
                props: {
                    id: 'skills-terminal',
                    template: 'darkTerminal',
                    title: '$ ls -la skills/',
                    backgroundColor: 'bg-gray-900',
                    terminalTheme: 'matrix',
                    skills: [
                        { name: 'JavaScript', level: 95, category: 'Languages' },
                        { name: 'Python', level: 90, category: 'Languages' },
                        { name: 'TypeScript', level: 88, category: 'Languages' },
                        { name: 'React', level: 92, category: 'Frontend' },
                        { name: 'Vue.js', level: 85, category: 'Frontend' },
                        { name: 'Node.js', level: 88, category: 'Backend' },
                        { name: 'Express', level: 87, category: 'Backend' },
                        { name: 'MongoDB', level: 83, category: 'Database' },
                    ],
                },
            },
            {
                type: 'Projects',
                props: {
                    id: 'projects-terminal',
                    template: 'darkTerminal',
                    title: '$ git log --projects',
                    email: 'dev@terminal.com',
                    backgroundColor: 'bg-black',
                    terminalTheme: 'matrix',
                    projects: [
                        {
                            title: 'Terminal Portfolio',
                            description: 'Interactive terminal-style portfolio website',
                            image: 'https://placehold.co/400x250/000000/00FF00?text=Terminal+Portfolio',
                            technologies: 'React, CSS3, JavaScript',
                            status: 'ACTIVE',
                            command: 'npm start portfolio',
                        },
                        {
                            title: 'Code Editor',
                            description: 'Web-based code editor with syntax highlighting',
                            image: 'https://placehold.co/400x250/000000/00FF00?text=Code+Editor',
                            technologies: 'Vue.js, Monaco Editor, Node.js',
                            status: 'BETA',
                            command: 'npm run dev',
                        },
                        {
                            title: 'CLI Tool Suite',
                            description: 'Collection of command-line utilities for developers',
                            image: 'https://placehold.co/400x250/000000/00FF00?text=CLI+Tools',
                            technologies: 'Node.js, Commander.js, Chalk',
                            status: 'STABLE',
                            command: 'npm install -g cli-tools',
                        },
                    ],
                },
            },
            {
                type: 'Footer',
                props: {
                    id: 'footer-terminal',
                    template: 'darkTerminal',
                    companyName: 'TerminalPort',
                    description: 'Executing digital solutions with precision and efficiency. Every command crafted for optimal performance.',
                    tagline: 'root@future:~$ innovation --execute',
                    email: 'admin@terminalport.dev',
                    phone: '+1 (800) TERM-CMD',
                    address: 'Terminal District\n/home/cyber/workspace\nServer Room 404',
                    socialLinks: 'GitHub|https://github.com\nLinkedIn|https://linkedin.com\nTwitter|https://twitter.com\nStack|https://stackoverflow.com',
                    quickLinks: 'About\nProjects\nServices\nExperience\nContact',
                    backgroundColor: 'bg-black',
                    terminalTheme: 'matrix',
                },
            },
        ],
    },
    artist: {
        name: 'Artist Portfolio',
        description: 'Creative and colorful theme designed for artists and creative professionals',
        preview: artistPreview,
        content: [
            {
                type: 'Navbar',
                props: {
                    id: 'navbar-artist',
                    template: 'horizontal',
                    logoText: 'ARTISAN',
                    backgroundColor: 'bg-gradient-to-r from-pink-50 to-purple-50',
                    textColor: 'text-purple-800',
                    menuItems: [
                        { label: 'Home', href: '#home' },
                        { label: 'About', href: '#about' },
                        { label: 'Gallery', href: '#projects' },
                        { label: 'Services', href: '#services' },
                        { label: 'Contact', href: '#contact' },
                    ],
                },
            },
            {
                type: 'Hero',
                props: {
                    id: 'hero-artist',
                    template: 'artist',
                    name: 'Sofia Martinez',
                    title: 'Contemporary Visual Artist',
                    description: 'Creating vibrant digital and traditional art that speaks to the soul. Specializing in abstract expressionism and mixed media installations.',
                    image: 'https://placehold.co/400x400/F59E0B/FFFFFF?text=Artist+Portrait',
                    backgroundColor: 'artistic',
                    accentColor: 'orange',
                    artworkImage1: 'https://placehold.co/600x400/8B5CF6/FFFFFF?text=Featured+Artwork',
                    artworkImage2: 'https://placehold.co/400x400/EF4444/FFFFFF?text=Digital+Art',
                    artworkImage3: 'https://placehold.co/400x350/10B981/FFFFFF?text=Mixed+Media',
                    yearsActive: '8+',
                    artworkCount: '150+',
                    exhibitionsCount: '15',
                    resumeUrl: '/shared/artist-resume',
                },
            },
            {
                type: 'About',
                props: {
                    id: 'about-artist',
                    template: 'artist',
                    title: 'My Artistic Journey',
                    content:
                        'Art has been my language of expression for over a decade. I draw inspiration from the interplay of light and emotion, creating pieces that invite viewers to explore their own inner landscapes.',
                    backgroundColor: 'artistic',
                    accentColor: 'orange',
                    resumeUrl: '/shared/artist-resume',
                    studioImage: 'https://placehold.co/500x600/8B5CF6/FFFFFF?text=Artist+Studio',
                    processImage1: 'https://placehold.co/300x300/EF4444/FFFFFF?text=Art+Process',
                    processImage2: 'https://placehold.co/300x300/10B981/FFFFFF?text=Creative+Tools',
                    artisticMediums: [
                        { medium: 'Digital Art', experience: 'Expert' },
                        { medium: 'Oil Painting', experience: 'Advanced' },
                        { medium: 'Mixed Media', experience: 'Intermediate' },
                        { medium: 'Photography', experience: 'Advanced' },
                    ],
                    yearsActive: '8+',
                    artworkCount: '150+',
                    exhibitionsCount: '25',
                    showCTA: true,
                },
            },
            {
                type: 'Skills',
                props: {
                    id: 'skills-artist',
                    template: 'artist',
                    title: 'Artistic Skills',
                    backgroundColor: 'bg-gradient-to-b from-pink-50 via-rose-50 to-pink-50',
                    accentColor: 'artistic',
                    skills: [
                        { name: 'Digital Illustration', level: 95, category: 'Digital' },
                        { name: 'Oil Painting', level: 90, category: 'Traditional' },
                        { name: 'Photography', level: 85, category: 'Digital' },
                        { name: 'Mixed Media', level: 88, category: 'Traditional' },
                        { name: 'Color Theory', level: 93, category: 'Foundation' },
                        { name: 'Composition', level: 91, category: 'Foundation' },
                    ],
                    skillDemoImage: 'https://placehold.co/400x300/F59E0B/FFFFFF?text=Skill+Demo',
                },
            },
            {
                type: 'Projects',
                props: {
                    id: 'projects-artist',
                    template: 'grid',
                    title: 'Featured Artworks',
                    email: 'sofia@artisan.com',
                    backgroundColor: 'bg-gradient-to-b from-pink-50 via-rose-50 to-pink-50',
                    accentColor: 'orange',
                    projects: [
                        {
                            title: 'Ethereal Dreams',
                            description: 'Abstract digital painting exploring the subconscious mind',
                            image: 'https://placehold.co/400x300/F59E0B/FFFFFF?text=Ethereal+Dreams',
                            technologies: 'Digital Art, Photoshop, Procreate',
                            category: 'Digital Art',
                        },
                        {
                            title: 'Urban Symphony',
                            description: 'Mixed media installation capturing city life rhythms',
                            image: 'https://placehold.co/400x300/F59E0B/FFFFFF?text=Urban+Symphony',
                            technologies: 'Mixed Media, Acrylic, Digital',
                            category: 'Installation',
                        },
                        {
                            title: 'Portrait Series',
                            description: 'Oil painting collection celebrating human diversity',
                            image: 'https://placehold.co/400x300/F59E0B/FFFFFF?text=Portrait+Series',
                            technologies: 'Oil Paint, Canvas, Traditional',
                            category: 'Traditional Art',
                        },
                    ],
                },
            },
            {
                type: 'Contact',
                props: {
                    id: 'contact-artist',
                    template: 'artist',
                    title: "Let's Create Together",
                    description: 'Interested in commissioning artwork or collaborating on a project?',
                    backgroundColor: 'bg-gradient-to-br from-rose-50 via-pink-50 to-purple-50',
                    accentColor: 'artistic',
                    email: 'sofia@artisan.com',
                    phone: '+1 (555) 234-5678',
                    location: 'Los Angeles, CA',
                    socialLinks: [
                        { platform: 'Instagram', url: '#', icon: 'instagram' },
                        { platform: 'Behance', url: '#', icon: 'behance' },
                        { platform: 'Etsy', url: '#', icon: 'etsy' },
                    ],
                },
            },
        ],
    },
    darkCyberSec: {
        name: 'Dark Cyber Security',
        description: 'Professional cybersecurity theme with dark aesthetics and security-focused content',
        preview: cyberSecurityPreview,
        content: [
            {
                type: 'Hero',
                props: {
                    id: 'hero-cybersec',
                    template: 'darkCyberSec',
                    name: 'Marcus Shield',
                    title: 'Senior Cybersecurity Analyst',
                    description:
                        'Protecting digital assets through advanced threat detection, penetration testing, and security architecture. Specialized in enterprise security and incident response.',
                    image: 'https://placehold.co/400x400/000000/00FFFF?text=SECURITY',
                    backgroundColor: 'bg-gradient-to-br from-gray-900 via-black to-gray-800',
                    accentColor: 'cyan',
                    securityCerts: '12+',
                    threatsBlocked: '50K+',
                    systemsSecured: '200+',
                    vulnerabilitiesFound: '1.2K+',
                    resumeUrl: '/shared/cybersec-resume-123',
                    specialization: 'Threat Intelligence & Incident Response',
                    yearsExperience: '10+',
                },
            },
            {
                type: 'About',
                props: {
                    id: 'about-cybersec',
                    template: 'darkCyberSec',
                    title: 'Security Profile',
                    content:
                        'Dedicated cybersecurity professional with extensive experience in threat hunting, vulnerability assessment, and security architecture. Committed to staying ahead of emerging threats and protecting organizational assets.',
                    profileImage: 'https://placehold.co/400x300/000000/00FFFF?text=Security+Professional',
                    backgroundColor: 'bg-gradient-to-br from-gray-900 via-black to-gray-800',
                    accentColor: 'cyan',
                    resumeUrl: '/shared/cybersec-resume-123',
                    specializations: [
                        { area: 'Threat Intelligence', level: 'Expert', icon: 'eye' },
                        { area: 'Incident Response', level: 'Expert', icon: 'shield' },
                        { area: 'Vulnerability Assessment', level: 'Advanced', icon: 'bug' },
                        { area: 'Security Architecture', level: 'Advanced', icon: 'lock' },
                        { area: 'Penetration Testing', level: 'Expert', icon: 'key' },
                        { area: 'Forensic Analysis', level: 'Advanced', icon: 'code' },
                    ],
                    certifications: [
                        { name: 'CISSP', issuer: '(ISC)²', year: '2022' },
                        { name: 'CEH', issuer: 'EC-Council', year: '2021' },
                        { name: 'GCIH', issuer: 'GIAC', year: '2023' },
                        { name: 'Security+', issuer: 'CompTIA', year: '2020' },
                    ],
                    yearsExperience: '10+',
                    threatsBlocked: '50K+',
                    systemsSecured: '200+',
                    incidentsHandled: '500+',
                },
            },
            {
                type: 'Skills',
                props: {
                    id: 'skills-cybersec',
                    template: 'darkCyberSec',
                    title: 'Security Arsenal',
                    backgroundColor: 'bg-black',
                    accentColor: 'cyan',
                    skills: [
                        { name: 'Penetration Testing', level: 95, category: 'Offensive Security' },
                        { name: 'Incident Response', level: 92, category: 'Defense' },
                        { name: 'Vulnerability Assessment', level: 93, category: 'Assessment' },
                        { name: 'Network Security', level: 90, category: 'Infrastructure' },
                        { name: 'Malware Analysis', level: 87, category: 'Forensics' },
                        { name: 'SIEM/SOAR', level: 88, category: 'Tools' },
                        { name: 'Risk Management', level: 85, category: 'Governance' },
                        { name: 'Compliance', level: 90, category: 'Governance' },
                    ],
                },
            },
            {
                type: 'Projects',
                props: {
                    id: 'projects-cybersec',
                    template: 'darkCyber',
                    title: 'Security Projects',
                    subtitle: 'Cybersecurity solutions and implementations',
                    backgroundColor: 'bg-black',
                    accentColor: 'cyan',
                    email: 'marcus@secure.tech',
                    projects: [
                        {
                            title: 'Enterprise SOC Implementation',
                            description:
                                'Designed and implemented 24/7 Security Operations Center for Fortune 500 company. Reduced incident response time by 60% through advanced automation and threat detection.',
                            image: 'https://placehold.co/400x300/000000/00FFFF?text=SOC+Implementation',
                            technologies: 'Splunk, IBM QRadar, Phantom SOAR, Python',
                            status: 'Completed',
                        },
                        {
                            title: 'Threat Hunting Program',
                            description: 'Developed proactive threat hunting methodology and tools. Detected 95% more advanced persistent threats through custom detection rules and analytics.',
                            image: 'https://placehold.co/400x300/000000/00FFFF?text=Threat+Hunting',
                            technologies: 'MITRE ATT&CK, Sigma Rules, Elastic Stack, YARA',
                            status: 'Active',
                        },
                        {
                            title: 'Security Automation Framework',
                            description: 'Built automated incident response and remediation system. Automated 80% of routine security tasks, improving response efficiency significantly.',
                            image: 'https://placehold.co/400x300/000000/00FFFF?text=Security+Automation',
                            technologies: 'Python, Ansible, REST APIs, Docker',
                            status: 'Beta',
                        },
                    ],
                },
            },
            {
                type: 'Awards',
                props: {
                    id: 'awards-cybersec',
                    template: 'showcase',
                    title: 'Certifications & Recognition',
                    subtitle: 'Security certifications and professional achievements',
                    backgroundColor: 'bg-gradient-to-br from-gray-900 via-black to-gray-800',
                    accentColor: 'cyan',
                    awards: [
                        {
                            title: 'CISSP - Certified Information Systems Security Professional',
                            organization: '(ISC)²',
                            date: '2020',
                            description: 'Advanced cybersecurity leadership certification demonstrating expertise in security architecture and risk management.',
                            category: 'certification',
                            icon: '🛡️',
                            image: 'https://placehold.co/80x80/000000/00FFFF?text=CISSP',
                        },
                        {
                            title: 'CEH - Certified Ethical Hacker',
                            organization: 'EC-Council',
                            date: '2019',
                            description: 'Ethical hacking and penetration testing certification for offensive security expertise.',
                            category: 'certification',
                            icon: '🔐',
                            image: 'https://placehold.co/80x80/000000/00FFFF?text=CEH',
                        },
                        {
                            title: 'GCIH - GIAC Certified Incident Handler',
                            organization: 'GIAC/SANS',
                            date: '2021',
                            description: 'Incident response and computer forensics certification for advanced threat hunting.',
                            category: 'certification',
                            icon: '🔍',
                            image: 'https://placehold.co/80x80/000000/00FFFF?text=GCIH',
                        },
                        {
                            title: 'Security+ - CompTIA Security+',
                            organization: 'CompTIA',
                            date: '2020',
                            description: 'Foundational cybersecurity certification covering core security concepts and practices.',
                            category: 'certification',
                            icon: '🔒',
                            image: 'https://placehold.co/80x80/000000/00FFFF?text=SEC+',
                        },
                    ],
                },
            },
            {
                type: 'Contact',
                props: {
                    id: 'contact-cybersec',
                    template: 'darkCyberSec',
                    title: 'Secure Communication',
                    description: 'Ready to discuss cybersecurity consulting or collaboration opportunities?',
                    backgroundColor: 'bg-black',
                    accentColor: 'cyan',
                    email: 'marcus@secure.tech',
                    phone: '+1 (555) 345-6789',
                    location: 'Washington, DC',
                    socialLinks: [
                        { platform: 'LinkedIn', url: '#', icon: 'linkedin' },
                        { platform: 'GitHub', url: '#', icon: 'github' },
                    ],
                },
            },
        ],
    },
};
